services:
  ignore-merger:
    image: fakuivan/syncthing-ignore-merger:latest
    build: .
    command:
      - from-docker-labels
      - /folder_ignore/.stignore
      - /default_ignore/.stignore
      - /tmp/ignores_test/folder/
      - io.github.fakuivan.stmerger.stignore
      - io.github.fakuivan.stmerger.subdir
    volumes:
      - /tmp/ignores_test/ignores/:/ignores:ro
      - /tmp/ignores_test/folder_ignore:/folder_ignore
      - /tmp/ignores_test/default:/default_ignore:ro
      - /var/run/docker.sock:/var/run/docker.sock

  auto_name:
    image: alpine
    depends_on:
      - ignore-merger
    volumes:
      - /tmp/ignores_test/folder/auto_name:/synched:rw
      - /tmp/ignores_test/folder_ignore:/folder_ignore:ro
    labels:
      io.github.fakuivan.stmerger.stignore: |
        /dir1
        /dir2
        dir3
        a_file.*
    command: 
      - sh
      - -c
      - |
        sleep 3
        cat /folder_ignore/.stignore
